packages:
  - "packages/*"

# don't use it since module federation doesn't work well with pnpm catalog
catalog:
  react: ^18.3.1
  react-dom: ^18.3.1

  "@module-federation/enhanced": ^0.17.1
  "@module-federation/rsbuild-plugin": ^0.17.1

  "@mui/material": ^7.2.0
  "@emotion/react": ^11.14.0
  "@emotion/styled": ^11.14.0
